[package]
name = "wasm_experiment"
version = "0.1.0"
authors = ["thiolliere <gui.thiolliere@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
stdweb = "0.1"
winit = "0.9"
lazy_static = "1"
